# native package workflows
name: build native distribution
on:
  release:
    types:
      - published
jobs:
  package:
    name: Building native distribution
    strategy:
      matrix:
        os: [ macos-latest, ubuntu-latest, windows-latest ]
    runs-on: ${{ matrix.os }}

    steps:
      # 检出仓库代码
      - name: Check out repo
        uses: actions/checkout@v2.4.0


