# native package workflows
name: build and release native distribution
on: push
#  push:
#    tags:
#      - v*.*.**


jobs:
  package:
    name: Building native distribution
    strategy:
      matrix:
        os: [ macos-latest, ubuntu-latest, windows-latest ]
    runs-on: ${{ matrix.os }}



    steps:
      # 检出仓库代码
      - name: Check out repo
        uses: actions/checkout@v2

      # Setup java
      - name: Setup Java 17
        uses: actions/setup-java@v2
        with:
          # See 'Supported distributions' for available options
          distribution: 'zulu'
          java-version: '17'
          cache: 'gradle'

      # Gradle
      #      - name: Gradle Wrapper Validation
      #        uses: gradle/wrapper-validation-action@v1.0.4

      - name: Gradle building native distribution
        uses: gradle/gradle-build-action@v2
        with:
          gradle-version: 7.3.3
          arguments: build packageAndMove

      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v2.3.1
        with:
          name: distributions
          path: build/compose/binaries/main/distributions/**

      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v2.3.1
        with:
          name: changelog.md
          path: .changelog/${{ github.ref_name }}.md


  release:
    runs-on: ubuntu-latest
    needs: package

    permissions:
      contents: write

    steps:

      - name: Download artifacts
        uses: actions/download-artifact@v2
        with:
          name: distributions
          path: distributions

      - name: Download artifacts
        uses: actions/download-artifact@v2
        with:
          name: changelog.md
          path: changelog


      # Releases.
      - name: Create github releases
        uses: softprops/action-gh-release@v0.1.14
        with:
          files: build/compose/binaries/main/distributions/**
          body_path: changelog/changelog.md
          generate_release_notes: true
          draft: true